CREATE TABLE "GCG_3677_INV_ATTR" (
 "PART" CHAR(20),
 "LOC" CHAR(2),
 "FLAG_ROHS" BIT DEFAULT '0' NOT NULL,
 "FLAG_DFARS" BIT DEFAULT '0' NOT NULL,
 "FLAG_ITAR" BIT DEFAULT '0' NOT NULL,
 "FLAG_PASSIVATION" BIT DEFAULT '0' NOT NULL,
 "FLAG_PLATING" BIT DEFAULT '0' NOT NULL,
 "FLAG_HEATTREAT" BIT DEFAULT '0' NOT NULL,
 "FLAG_PPAP" BIT DEFAULT '0' NOT NULL,
 "FLAG_FAI" BIT DEFAULT '0' NOT NULL,
 "FLAG_REACH" BIT DEFAULT '0' NOT NULL,
 "SPECIAL_INSTRUCTIONS" CHAR(30) );